root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main.exe ./cmd/server"
  bin = "tmp/main.exe"
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
